config/routes.rb
Rails.application.routes.draw do devise_for :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only:[:index, :show] do
    resources :posts, only:[:index, :new, :show, :create, :destroy] do
      resources  :comments, only:[:index, :new, :create, :destroy]
      resources  :likes, only:[:new, :create]
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  before_save do
    update_post_comments_counter
  end

  def update_post_comments_counter
    post = Post.find_by(id: post_id)
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_post_likes_counter

  def update_post_likes_counter
    post = Post.find_by(id: post_id)
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }

  before_save do
    update_user_posts_counter
  end

  after_destroy :decrement_user_posts_counter

  def update_user_posts_counter
    user = User.find_by(id: author.id)
    user.increment!(:posts_counter)
  end

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def decrement_user_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def three_most_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :posts_counter) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to "/users/#{params[:user_id]}/posts/#{params[:post_id]}"
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy

    respond_to do |format|
      format.html do
        redirect_to user_post_path, notice: 'Comment was destroyed successfully.'
      end
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @like = Like.new
    @post = Post.find(params[:id])
  end

  def new
    @like = Like.new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(post: @post, author: current_user)

    if @like.save
      redirect_to "/users/#{params[:user_id]}/posts/#{params[:post_id]}"
    else
      redirect_to :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.likes_counter = 0
    @post.comments_counter = 0

    if @post.save
      redirect_to "/users/#{params[:user_id]}/posts"
    else
      render :new
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy

    respond_to do |format|
      format.html { redirect_to "/users/#{params[:user_id]}/posts", notice: 'Post was deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/comments.html.erb
<div>

    <% if @comment.errors.any? %>
        <div class='error'>
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @comment.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end%>



    <%= form_with url:'/users/3/posts/1/comments', model: @comment do |form| %>
        <div>
            <%= form.label :text,'You can drop your comments here' %>
            <%= form.text_field :text %>
        </div>

        <%= form.submit 'Create A New Post'%>
    <% end %>

</div>

app/views/comments/index.html.erb
<div class="user">
  <% @comments.each do |comment| %>
  <p class='user-link'>
      <%= comment.text %>
    </p>
   
   
  <% end %>

</div>

app/views/comments/new.html.erb
<div class='user'>

    <% if @comment.errors.any? %>
        <div class='error'>
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @comment.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end%>


   
        <%= form_with url:"/users/3/posts/#{params[:post_id]}/comments", model: @comment do |form| %>
        <div class='user-textarea'>
            <%= form.label :text,'You can drop your comments here' %>
            <%= form.text_area :text, size: '70x10' %>
        </div>

        <%= form.submit 'Submit'%>
        <% end %>
     

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggingapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class='user'>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

   
     </div>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
  <%= form_with model: @like, url: user_post_likes_path do |form| %>
  <%= form.hidden_field :post_id, value: @post.id %>

  <%= form.submit "Like" %>
<% end %>

app/views/partials/_post.html.erb
<div class='user-text'>
  <p>Post #<%= post.id%>:<%= post.title%></p>

  <p><%= post.text%></p>

   <div class='parameters'>
   
    <p class='user-post'>
    Comments:<span><%= post.comments_counter %></span>,
    Likes:<span><%= post.likes_counter %></span>
  </p>
       </div>
 
</div>

app/views/partials/_user.html.erb
  <%= link_to user_path(user) do %>

<div class='user-partial' >

<img src= '<%=user.photo %>' alt= 'user <%=user.name %>'/>

  <div class = 'users'>
    <p class='user-name'><%= user.name %></p>
    <p class='user-id'>(user id: <%= user.id %>)</p>

    <p class='user-post'>
      Number of post: <%=user.posts_counter %>
    </p>

   
  </div>
  
</div>

 <% end %>

app/views/posts/index.html.erb
<div class="user">
 
 <%= render 'partials/user', user: @user%>

 <% @posts.includes(:comments).each do |post| %> 
 
 
    <%= render 'partials/post', post: post, user: @user%>
   
    
 
    <div class='user-text'>
      <%post.five_most_recent_comments.each do |postcomment| %>
        <p>
          <span><%= postcomment.author.name %></span>:
          <span><%= postcomment.text %></span>
        </p>

      <% end %>
    </div>
   <a href="/users/<%= @user.id%>/posts/<%= post.id%>" ><button>View post #<%= post.id%></button></a>
    
 
  
  <a href="/users/<%= @user.id%>/posts/new" ><button style="margin-top: 10px;">Create new post</button></a>
  <% end %>

  
  <div class='btn-paginate'>
  
  <button>Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<div class='user'>

    <% if @post.errors.any? %>
        <div class='error'>
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @post.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end%>



    <%= form_with url:"/users/#{params[:user_id]}/posts", model: @post do |form| %>
        <div class='user-text-field'>
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>

        <div class='user-text-field'>
            <%= form.label :text %>
            <%= form.text_area :text, size: '60x10' %>
        </div>

        <%= form.submit 'Create A New Post'%>
    <% end %>

</div>

app/views/posts/show.html.erb
<div class="user">

 <div class='user-text'>
    <div class='post-detail'>
      <p>Post #<%=@post.id %> by <%=@post.author.name %></p>
      <p>
        Comments:<span><%= @post.comments_counter %></span>,
        Likes: <span><%= @post.likes_counter %></span>
      </p>
    </div>
    <p><%=@post.text %></p>
     
  </div>
  

  <div class='user-text'>
    <%@post.five_most_recent_comments.each do |postcomment| %>
      <p>
        <span><%= postcomment.id %></span>:<span><%= postcomment.author.name %></span>:
        <span><%= postcomment.text %></span>
      </p>
      <% if can?(:destroy, postcomment) %>
      <%= button_to 'Delete comment', user_post_comment_path(params[:user_id],@post,postcomment), method: :delete %>
      <% end %>
    <% end %>
  </div>

<% if can?(:destroy, @post) %>
  <%= button_to 'Delete this post', user_post_path(@post.id), method: :delete %>
<% end %>
  <a href='/users/<%= @user.id%>/posts/<%= @post.id%>/likes/new' ><button style="margin-left: 150px;">Like this post</button></a>
  <a href='/users/<%= @user.id%>/posts/<%= @post.id%>/comments/new' ><button style="margin-left: 150px;">Add a comment</button></a>
  
</div>

app/views/users/index.html.erb
<div class="user">
  <% @users.each do |user| %>

    <%= render 'partials/user', user: user%>
   
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user" >
    <%= render 'partials/user', user: @user%>

    <div class='user-bio'>
      <p>bio </p>
      <p> <%=@user.bio %> </p>
    </div>

    <% @user.three_most_recent_post.each do |post| %>
      <%= link_to @user_post_path do %>
      <div class='user-text'>
        <p>Post #<%= post.id %></p>
        <p><%= post.text %></p>
         <div class='parameters'>
        <p class='user-post'> Comments:<span><%= post.comments_counter %></span>, Likes: <span><%= post.likes_counter %></span> </p>
       </div>
      </div>
      <% end %>
     
    <% end %>
    <a href="/users/<%= @user.id%>/posts/new" ><button style="margin-top: 10px;">Create new post</button></a>
    <a href="/users/<%= @user.id%>/posts" ><button>See all Posts</button></a>

</div>